sexuality = [
    r' sex',
    r'gender',
    r'promiscu(ous|ity)',
    r' porn ',
    r'pornograph(y|ic)',
    r'erotic',
    r'horny',
    r'prostitut',
    r'whore',
    r'hooker',
    r' slut ',
    r'penis',
    r'vagina',
    r'intimate',
    r'okcupid',
    r'grindr',
    r'lgbt',
    r'lesbian',
    r'gay',
    r'bisexual',
    r'trans(gender|sexual)',
    r'queer',
    r'non ?binary',
    r'hetero',
    r'attracted',
    r'fuck',
    r'phil[ei]',
    r'identity',
    r'divers[ei]',
    r'abstinen',
    r' ?pride ',
    r'consent',
]

financial = [
    r'poor',
    r'poverty',
    r'struggl(ing|er)',
    r'wealth(y|iest)',
    r'gambl(ing|er)',
    r'betting',
    r' credit ?(level|score|crunched)?',
    r'(un)?insured',
    r'insurance',
    r'shallow ?pocket',
    r'urban ?survivor',
    r'tight ?money',
    r'tough ?times',
    r'retir(ement|ing|ed|ee)',
    r'diamonds',
    r'pearls',
    r'champagne',
    r'luxury',
    r'income',
    r'affluent',
]

race = [
    r'ethnic',
    r'migra(nt|ted|tion)',
    r'minorit(y|ies)',
    r'multicultural',
    r'caucasian',
    r'african',
    r'hispanic',
    r'latin(o|a)',
    r'arabic',
    r'middle ?east',
    r'asian',
    r'african ?american',
    r'indian',
    r'pacific ?islander',
    r'white',
    r' native',
    r'foreign',
    r'rac(e|ism)',
    r'refuge',
    r'inclusion',

]

religion = [
    r'religio(n|ous)',
    r' faith',
    r'christian',
    r'catholic',
    r'protestant',
    r'muslim',
    r'islam',
    r' jew',
    r'judais',
    r'buddhis[tm]',
    r'hinduis[tm]',
    r'atheis[tm]',
    r'spiritual',
    r'church',
    r'mosque',
    r'synagog',
    r'temple',
    r'kippa',
    r'shabbat',
    r'hijab',
    r'niqab',
    r'burqa',
    r'chador',
    r'belie[fv]',
    r'orientation',
    r'worship',
    r'communion',
    r'bibl(e|icial)',
    r'ramadan',
    r'hajj',
    r' eid ',
    r'sh?abbath?',
    r'kosher',

]

health = [
    r'disease',  # treatment general
    r'illness',
    r' pain ',
    r'fatigue',
    r'surgery',
    r'medic(al|ine)',
    r'arthritis',
    r'hypertension',
    r'fibromyalgia',
    r'pancrea(s|tic)',
    r'sleep ?apnea',
    r'migraine',
    r'asthma',
    r' dvt ',
    r'kidney ?disease',
    r'constipat(ion|ed)',
    r' copd ',
    r'smok(ing|er)',
    r'injur(ed|y)',
    r'osteopa',
    r'prostate',
    r'assault',
    r'violence',
    r' chronic ',
    r'insulin',
    r'hypertension',
    r'dysfunction',


    r'obes(e|ity)',  # Obesity/heart
    r'(over)?weight( loss)?',
    r'diabet(es|ic)',
    r'atrial fibrillation',
    r'blood ?(pressure|clot)',
    r'heart ?(disease|failure|condition)',
    r'stroke',
    r'coronary',
    r'artery',
    r'thrombo',


    r'alzheimer',  # Neurodegenerative
    r'dementia',
    r'parkinson',
    r'nuplazid',
    r' ms ',
    r'multiple ?(sclerosis|sklerose)',
    r'huntington',
    r'cerebral ?palsy',


    r'cancer',  # Cancer and rel.
    r'tobacco',
    r'respiratory',
    r'leukemia',
    r'lymphoma',
    r'tumor',


    r'pregnan(t|cy)',  # sexual health
    r'matern(al|ity)',
    r'abort(ion|ed)',
    r'family planning',
    r'parent(hood)?',
    r'miscarriage',
    r'menopause',
    r'(in)?fertil(e|ity)',
    r'ovulat(e|ion)',
    r'viagra',
    r'cialis',
    r'erectile ?dysfunction',
    r'contracepti(ve|ion)',
    r'urinary ?tract ?infection',
    r' uti ',
    r'menstrua(l|ting|te)',

    r'hearing ?(aid|loss)',  # disabilities
    r' deaf(ness)? ',
    r'paraplegi[aec]',
    r'disab(led|ility)',
    r'blind',
    r'impair(ment|ed)',



    r'autis(m|tic)',  # psychological
    r' adh(d|s) ',
    r'anxiety',
    r'psych(olog|iatr)',
    r'depress(ed|ion)',
    r'(?!environ)mental',
    r'addict',
    r'alcohol',
    r'drugs',
    r'cannabis',
    r'painkiller',
    r'opi(oid|um)',
    r'abuse',
    r'bipolar',
    r'disorder',
    r'schizoph',
    r'panic',
    r'insomnia',
    r'sleep disorder',
    r'neurodiver',


]

personality = [
    r'tattoo',
    r'hipster',
    r'dog ?owner',
    r'trendy moms',
    r'pension',
    r'aspirations',
    r'dreams',
    r'happiness',
    r' lov(e|ing) ',
    r'lone ?wolve',
    r'emotional',
    r'rebellious',
    r'self ?image',
    r'concern(ed)?'
    r'confident',
    r'social',
    r'shopp(er|ing)',
    r'extraver(sion|t)',
    r'neurotic(ism)?',
    r'openness',
    r'conscientious',
    r'agreeable',
    r'general ?attitude',
    r'dealing ?with ?stress',
    r'romantic',
    r'divorce',
    r'widow',
    r'convict',
    r' weak(ness| )',
]

political = [
    r'unionized',
    r'(labou?r|trade) ?union',
    r'politic',

    r'advoca(cy|te)',  # advocacy
    r'support(er)?',
    r'vot(er|ed|ing)',
    r'newspaper',
    r'subscri(ber|ption)',

    r'conservative',  # political orientation
    r'liberal',
    r'progressive',
    r'communis[tm]',
    r'socialis[tm]',
    r'centris[tm]',
    r'(left|right) ?wing',
    r'secular',
    r'democra(t|cy)',
    r'radical',
    r'authoritarian',
    r'breitbart',

    r'terror',  # specific subjects
    r'marijuana',
    r' weed ',
    r'cannabis',
    r'gun ?(control|right)',
    r'equality',
    r'immigra(nt|tion)',
    r'aslyum',
    r'environment(al)?',
    r'climate ?change',
    r'global ?warming',
    r'conservation',
    r'organized ?labor',
    r'pro ?(choice|life)',
    r'animal ?rights',
    r'defund ?police',
    r'black ?lives ?matter',
    r' blm ',
    r'polic(y|ies)',
    r'military',
    r'ukraine',
    r'russia',
    r'police',
    r'crim(e|inal)',
    r'covid',
    r'corona',
    r'diesel(affae?re|gate)',
    r'justice',
    r'law ?and ?order',
    r'tradition',
    r'demograph',
    r'cannabis',
    r'gun ?(control|right)',
    r'human ?rights',


    r'worker[s\' ]*rights',  # Union support
    r'(labou?r|trade) ?union',
    r'labou?r',
    r' wages? ',

]

children = [
    r'child(ren)?',
    r' kid\'?s? ',
    r' minors? ',
    r'under ?(1[3-8]|age)',
    r' m[ou]ms? ',
    r'mother',
    r'father',
    r' dads? '
]
